name = "defi-simulator"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = false

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
